name: publishing_media_demo

profile: publishing_media_demo

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  publishing_media_demo:
    +schema: raw
    +quote_columns: false

models:
  publishing_media_demo:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: ephemeral
